require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/phases", type: :request do
  
  # Phase. As you add validations to Phase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Phase.create! valid_attributes
      get phases_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      phase = Phase.create! valid_attributes
      get phase_url(phase)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_phase_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      phase = Phase.create! valid_attributes
      get edit_phase_url(phase)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Phase" do
        expect {
          post phases_url, params: { phase: valid_attributes }
        }.to change(Phase, :count).by(1)
      end

      it "redirects to the created phase" do
        post phases_url, params: { phase: valid_attributes }
        expect(response).to redirect_to(phase_url(Phase.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Phase" do
        expect {
          post phases_url, params: { phase: invalid_attributes }
        }.to change(Phase, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post phases_url, params: { phase: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested phase" do
        phase = Phase.create! valid_attributes
        patch phase_url(phase), params: { phase: new_attributes }
        phase.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the phase" do
        phase = Phase.create! valid_attributes
        patch phase_url(phase), params: { phase: new_attributes }
        phase.reload
        expect(response).to redirect_to(phase_url(phase))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        phase = Phase.create! valid_attributes
        patch phase_url(phase), params: { phase: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested phase" do
      phase = Phase.create! valid_attributes
      expect {
        delete phase_url(phase)
      }.to change(Phase, :count).by(-1)
    end

    it "redirects to the phases list" do
      phase = Phase.create! valid_attributes
      delete phase_url(phase)
      expect(response).to redirect_to(phases_url)
    end
  end
end
