require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sub_tasks", type: :request do
  
  # SubTask. As you add validations to SubTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SubTask.create! valid_attributes
      get sub_tasks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sub_task = SubTask.create! valid_attributes
      get sub_task_url(sub_task)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sub_task_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sub_task = SubTask.create! valid_attributes
      get edit_sub_task_url(sub_task)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SubTask" do
        expect {
          post sub_tasks_url, params: { sub_task: valid_attributes }
        }.to change(SubTask, :count).by(1)
      end

      it "redirects to the created sub_task" do
        post sub_tasks_url, params: { sub_task: valid_attributes }
        expect(response).to redirect_to(sub_task_url(SubTask.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SubTask" do
        expect {
          post sub_tasks_url, params: { sub_task: invalid_attributes }
        }.to change(SubTask, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sub_tasks_url, params: { sub_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sub_task" do
        sub_task = SubTask.create! valid_attributes
        patch sub_task_url(sub_task), params: { sub_task: new_attributes }
        sub_task.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sub_task" do
        sub_task = SubTask.create! valid_attributes
        patch sub_task_url(sub_task), params: { sub_task: new_attributes }
        sub_task.reload
        expect(response).to redirect_to(sub_task_url(sub_task))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sub_task = SubTask.create! valid_attributes
        patch sub_task_url(sub_task), params: { sub_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sub_task" do
      sub_task = SubTask.create! valid_attributes
      expect {
        delete sub_task_url(sub_task)
      }.to change(SubTask, :count).by(-1)
    end

    it "redirects to the sub_tasks list" do
      sub_task = SubTask.create! valid_attributes
      delete sub_task_url(sub_task)
      expect(response).to redirect_to(sub_tasks_url)
    end
  end
end
